
all: 
	@echo done


# pathogen
all:  vim-pathogen.zip
vim-pathogen.zip:
	wget -O $@ https://github.com/tpope/vim-pathogen/archive/master.zip


# incsearch.vim
# https://github.com/haya14busa/incsearch.vim
# all:  incsearch.vim-master.zip
# incsearch.vim-master.zip:
# 	wget -O $@ https://github.com/haya14busa/incsearch.vim/archive/master.zip

# https://github.com/haya14busa/vim-asterisk
all: vim-asterisk-master.zip
vim-asterisk-master.zip:
	wget -O $@ https://github.com/haya14busa/vim-asterisk/archive/master.zip

all: vim-colors-solarizedvim-colors-solarized.zip
vim-colors-solarizedvim-colors-solarized.zip:
	wget -O $@ https://github.com/altercation/vim-colors-solarized/archive/master.zip

all: vim-noctu-master.zip
vim-noctu-master.zip:
	wget -O $@  https://github.com/noahfrederick/vim-noctu/archive/master.zip

########################
# Files
#

# NERDTree
all: nerdtree.zip
nerdtree.zip:
	wget -O $@ https://github.com/scrooloose/nerdtree/archive/master.zip

# MRU
# all:   mru.zip
# mru.zip:
# 	wget -O $@ https://github.com/yegappan/mru/archive/master.zip

# ctrlp
all: ctrlp.zip
ctrlp.zip:
	wget -O $@ https://github.com/roxma/ctrlp.vim/archive/master.zip

#
# Files
########################



########################
# general editing
#

# surround
# all: vim-surround.zip
# vim-surround.zip:
# 	wget -O $@ https://github.com/tpope/vim-surround/archive/master.zip

# tabular
all: tabular.zip
tabular.zip: 
	wget -O $@ https://github.com/godlygeek/tabular/archive/master.zip

#
# general editing
########################

# Conque
# all: conque.zip
# conque.zip:
# 	wget -O $@ https://github.com/vim-scripts/Conque-Shell/archive/master.zip


all: vim-easymotion.zip
vim-easymotion.zip:
	wget -O $@ https://github.com/Lokaltog/vim-easymotion/archive/master.zip




# all: powerline.zip
#powerline.zip:
#	wget -O $@ https://github.com/powerline/powerline/archive/master.zip


########################
# View
#

all: airline.zip
airline.zip:
	wget -O $@ https://github.com/bling/vim-airline/archive/master.zip

# all: accelerated-smooth-scroll.zip
# accelerated-smooth-scroll.zip:
# 	wget -O $@ https://codeload.github.com/yonchu/accelerated-smooth-scroll/zip/master

#
# View
########################



########################
# C / C++
#

all: tagbar.zip
tagbar.zip:
	wget -O $@ https://github.com/majutsushi/tagbar/archive/master.zip

#
# C / C++
########################


########################
# html, xml
#

all: vim-javascript-syntax.zip
vim-javascript-syntax.zip:
	wget -O $@ https://github.com/jelera/vim-javascript-syntax/archive/master.zip	

all: emmet-vim.zip
emmet-vim.zip:
	wget -O $@ https://github.com/mattn/emmet-vim/archive/master.zip

#
# html, xml
########################

# markdown
all:  vim-markdown.zip
vim-markdown.zip: tabular.zip
	wget -O $@ https://github.com/plasticboy/vim-markdown/archive/master.zip


# php
all: phpcomplete.vim.zip
phpcomplete.vim.zip: 
	wget -O $@ https://github.com/shawncplus/phpcomplete.vim/archive/master.zip

# golang
all: vim-go.zip
vim-go.zip:
	wget -O $@ https://github.com/fatih/vim-go/archive/master.zip


# # https://github.com/tpope/vim-dispatch#readme
# all: vim-dispatch.zip
# vim-dispatch.zip:
# 	wget -O $@ https://github.com/tpope/vim-dispatch/archive/master.zip


# use accelerated-smooth-scroll.zip instead
# all: vim-smooth-scroll.zip
# vim-smooth-scroll.zip:
# 	wget -O $@ https://codeload.github.com/terryma/vim-smooth-scroll/zip/master

# # Rainbow Parentheses Improved
# all: rainbow.zip
# rainbow.zip:
# 	wget -O $@ https://github.com/luochen1990/rainbow/archive/master.zip

# Can't match JavaScript inside html <script> tag
# matchit.zip:
# 	wget -O $@ https://github.com/tmhedberg/matchit/archive/master.zip


# This plugin is now working
# headlights.zip: 
#	wget -O $@ https://github.com/mbadran/headlights/archive/master.zip

